// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/SwissChildrensBookCover-ARavyW/App.tsx": () => import("../components/mockups/templates/SwissChildrensBookCover-ARavyW/App.tsx"),
  "./components/mockups/templates/WonderRouteFieldGuide/App.tsx": () => import("../components/mockups/templates/WonderRouteFieldGuide/App.tsx")
};
